<?php
return $apartments = [
    [
        'title' => 'AirShip unico e appartato con vista mozzafiato sulle Highlands',
        'description' => 'Rifugiati sulla terrazza di questa vacanza sostenibile e ammira le scintillanti costellazioni sotto un\'accogliente coperta di tartan. AirShip 2 è un iconico chalet in alluminio isolato progettato da Roderick James con vista sul Sound of Mull dalle finestre delle dragonfly. Airship002 è comodo, eccentrico e alla moda. Non finge di essere un hotel a cinque stelle. Le recensioni raccontano la storia. Se hai prenotato le date, dai un\'occhiata al nostro nuovo annuncio The Pilot House, Drimnin, che si trova sullo stesso sito di 4 acra.',
        'price' => '195',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '50',
        'image' => 'apartments_img/apartment_1.webp',
        'is_visible' => '1',
        'address' => 'Trieste, Friuli Venezia Giulia',
        'latitude' => '45.612206',
        'longitude' => '13.793689',
    ],
    [
        'title' => 'Igloo da neve',
        'description' => 'Igloo da neve con letti veri all\'interno. Bella atmosfera con luci a led e pareti bianche. Fuori dall\'igloo è possibile vedere l\'aurora boreale se siete fortunati. Vieni in Lapponia ed esplora la natura selvaggia. ',
        'price' => '150',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '50',
        'image' => 'apartments_img/apartment_2.webp',
        'is_visible' => '1',
        'address' => 'Trento, Trentino Alto Adige',
        'latitude' => '46.47153457679491',
        'longitude' => '10.604842973376854',
    ],
    [
        'title' => 'Mirror House North',
        'description' => 'Le Mirror Houses sono una coppia di case vacanza, situate nella meravigliosa cornice delle Dolomiti altoatesine, in uno splendido scenario di meli, appena fuori dalla città di Bolzano.
        Le case a specchio offrono un\'occasione unica per trascorrere una bella vacanza circondati da architettura contemporanea di altissimo livello e il paesaggio più sorprendente e la bellezza della natura ha da offrire.',
        'price' => '220',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '50',
        'image' => 'apartments_img/apartment_3.webp',
        'is_visible' => '1',
        'address' => 'Padova, Veneto',
        'latitude' => '45.39211658706266',
        'longitude' => '11.899235162327843',
    ],
    [
        'title' => 'Bumble Barn at Great Field Farm',
        'description' => 'Great Field Farm è situato in 45 ettari, tra cui giardini, paddock e il grande campo con diverse colture ogni anno.
        Bumble Barn è l\'aggiunta più recente ai nostri rifugi per vacanze eco-friendly. Costruito secondo gli standard della casa Passiv con tecnologia intelligente e un bel tetto di sedum vivente che le api amano.
        La vista dal salotto e dal patio sui campi aperti e sul cielo è mozzafiato, con la fauna selvatica tutt\' intorno.
        Veramente tranquillo e rurale, ma Canterbury, Folkestone, Hythe, tunnel della Manica a soli 10 minuti di auto.',
        'price' => '345',
        'rooms' => '3',
        'beds' => '5',
        'bathrooms' => '2',
        'square_meters' => '50',
        'image' => 'apartments_img/apartment_4.webp',
        'is_visible' => '1',
        'address' => 'Bologna, Emilia Romagna',
        'latitude' => '44.486444593668814',
        'longitude' => '11.33017627586655',
    ],
    [
        'title' => 'Il Pino',
        'description' => 'Vincitore della Categoria Globale "OMG" di Airbnb
        Il Pino è la tua esperienza unica nella foresta incontaminata di Tarvisio.
        Ti permetterà di soggiornare tra le Alpi e dormire sopra le cime degli alberi, guardando le montagne illuminate dalla luce della luna.
        La baita è sviluppata su tre livelli, ognuno dei quali offre un contatto diverso con la natura.
        La struttura offre pace assoluta, non ci sono vicini e vi si accede tramite una strada sterrata privata.',
        'price' => '222',
        'rooms' => '2',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '50',
        'image' => 'apartments_img/apartment_5.webp',
        'is_visible' => '1',
        'address' => 'Aosta, Valle d\'Aosta',
        'latitude' => '45.75268679161336',
        'longitude' => '7.291797651871921',
    ],
    [
        'title' => 'La casetta di Aldo',
        'description' => 'Se non vi piace Cosenza è perchè non siete venuti nella casetta di Aldo!',
        'price' => '5',
        'rooms' => '6',
        'beds' => '3',
        'bathrooms' => '1',
        'square_meters' => '60',
        'image' => 'apartments_img/apartment_6.webp',
        'is_visible' => '1',
        'address' => 'Cosenza, Calabria',
        'latitude' => '39.297841441972174',
        'longitude' => '16.253698184133462',
    ],
    [
        'title' => 'Romantico faro Toscano',
        'description' => 'Lighthouse Toscano è il posto unico dove trascorrere le tue vacanze. È perfettamente sistemato su una piccola isola a soli 500 metri dal mare. Questo bellissimo monumento storico è stato costruito nell\'anno 1896 ed è stato completamente ristrutturato nell\'anno 2021 per fornire sistemazioni di lusso e comfort ai suoi inquilini. Il faro è ancora in funzione. Si illumina fino al porto di Murter. Se mai sogni di svegliarti con il suono delle onde che affittano questo alloggio potrebbe realizzare i tuoi sogni.',
        'price' => '482',
        'rooms' => '3',
        'beds' => '2',
        'bathrooms' => '3',
        'square_meters' => '80',
        'image' => 'apartments_img/apartment_7.webp',
        'is_visible' => '1',
        'address' => 'Isola d\'Elba, Toscana',
        'latitude' => '42.86531635683331',
        'longitude' => '10.474005266298422',
    ],
    [
        'title' => 'Villa Front Lake',
        'description' => 'Villa Front Lake è una residenza di lusso senza pari sul lago di Como. Dotata di design e arredi spettacolari, viste panoramiche e splendidi giardini paesaggistici, questa storica villa con sette camere da letto offre un ambiente incomparabile di privacy e classe, rendendola forse la migliore casa vacanze per riunioni di famiglia o ospiti di matrimoni di destinazione sulle rive esclusive di Como.',
        'price' => '4816',
        'rooms' => '7',
        'beds' => '7',
        'bathrooms' => '7',
        'square_meters' => '220',
        'image' => 'apartments_img/apartment_8.webp',
        'is_visible' => '1',
        'address' => 'Stresa, Piemonte',
        'latitude' => '45.89061070138619',
        'longitude' => '8.526714896594466',
    ],
    [
        'title' => 'Camera matrimoniale Glicine in castello',
        'description' => 'Camera matrimoniale di lusso all\'interno dell\'appartamento del castello di Duchessa. Splendida vista sul giardino dalla camera da letto. La camera disponeva di bagno privato e aria condizionata',
        'price' => '195',
        'rooms' => '3',
        'beds' => '3',
        'bathrooms' => '1',
        'square_meters' => '60',
        'image' => 'apartments_img/apartment_9.webp',
        'is_visible' => '1',
        'address' => 'Genova, Liguria',
        'latitude' => '44.381598275563604',
        'longitude' => '9.044212216422222',
    ],
    [
        'title' => 'Villa Frascoli',
        'description' => 'Il Lago Maggiore si estende da questa imponente villa italiana, mentre le verdeggianti colline ondeggiano all\'orizzonte. Un atrio arioso, dettagliato con accenti in stile barocco, ti accoglie entrando. Gli interni sofisticati sono inondati di luce solare. Goditi un cocktail nella veranda prima di fare una piacevole passeggiata nel sontuoso giardino. Nelle vicinanze si trovano enoteche, gelaterie e caffetterie.',
        'price' => '3900',
        'rooms' => '8',
        'beds' => '11',
        'bathrooms' => '8',
        'square_meters' => '250',
        'image' => 'apartments_img/apartment_10.webp',
        'is_visible' => '1',
        'address' => 'Belluno, Veneto',
        'latitude' => '46.045506443130655',
        'longitude' => '12.250379390939957',
    ],
    [
        'title' => 'Tuscany Podere nella natura con aria condizionata',
        'description' => 'Il podere si trova all\'interno di una riserva naturale. L\'abitazione si sviluppa attorno a una caratteristica corte dove si trovano la grande carraia adibita a sala da pranzo/soggiorno, tre camere matrimoniali con bagno, la lavanderia, il BBQ e il forno a legna. Al primo piano della casa si trovano la grande cucina e altre tre stanze matrimoniali sempre con servizio privato. Il grande giardino ospita una piscina a effetto lago naturale ad acqua salata con zona aeroterapia.',
        'price' => '570',
        'rooms' => '6',
        'beds' => '10',
        'bathrooms' => '7',
        'square_meters' => '140',
        'image' => 'apartments_img/apartment_11.webp',
        'is_visible' => '1',
        'address' => 'Firenze, Toscana',
        'latitude' => '43.73097635865804',
        'longitude' => '11.275607062957217',
    ],
    [
        'title' => 'KANYUMBA_REKEM',
        'description' => 'Dove passeresti il tuo prossimo inverno/estate?
        Vuoi socializzare con la natura ? in un posto bellissimo e tranquillo?
        KANYEMBA
        può offrire a te e alla tua famiglia, e il suo amico è un ottimo piano
        minimo 2 notti per poter prenotare',
        'price' => '96 ',
        'rooms' => '2',
        'beds' => '1',
        'bathrooms' => '3',
        'square_meters' => '80',
        'image' => 'apartments_img/apartment_12.webp',
        'is_visible' => '1',
        'address' => 'Belluno, Veneto',
        'latitude' => '46.20707781060593',
        'longitude' => '12.19234553041554',
    ],
    [
        'title' => 'Nomadi alla fine di Bolzano',
        'description' => 'Nomadi, l\'hotel di domani cerca di coniugare il comfort di un hotel di lusso con la cura e il rispetto per l\'ambiente utilizzando energie rinnovabili e uno speciale sistema di raccolta dei rifiuti in modo da non generare un impatto sulla terra desolata.',
        'price' => '10',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '2',
        'image' => 'apartments_img/apartment_13.webp',
        'is_visible' => '1',
        'address' => 'Bolzano, Trentino-Alto Adige',
        'latitude' => '46.5056775907772',
        'longitude' => '11.360946826919694',
    ],
    [
        'title' => 'Hanok Private House',
        'description' => 'Hanok Stay Emotional Day si trova nel centro di Tarvisio, Jeonju Hanok Village. Le attrazioni nelle vicinanze (Concubine, la Cattedrale di Jeonjeon, Gyeonggi Pre-Gyeonggi, Hyanggyo, ecc.) sono a 5 minuti di distanza.
        Si trova accanto alla strada principale, con un sacco di grucce per il cibo, ed è un soggiorno Hanok pulito e abbastanza familiare.',
        'price' => '203',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '70',
        'image' => 'apartments_img/apartment_14.webp',
        'is_visible' => '1',
        'address' => 'Tarvisio, Friuli Venezia Giulia',
        'latitude' => '46.50019957416598',
        'longitude' => '13.618347935462694',
    ],
    [
        'title' => 'Mirror House Sud',
        'description' => 'Mirror Houses sono due casette immerse in uno stupendo scenario di meleti appena fuori a, nei meravigliosi dintorni delle Dolomiti altoatesine.
        Le Mirror Houses offrono un’occasione unica per trascorrere una stupenda vacanza circondati da architettura contemporanea dei più alti standard a stretto contatto con uno tra i più suggestivi paesaggi che la natura possa offrire.',
        'price' => '220',
        'rooms' => '2',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '110',
        'image' => 'apartments_img/apartment_15.webp',
        'is_visible' => '1',
        'address' => 'Roma, Lazio',
        'latitude' => '41.89512420420171',
        'longitude' => '12.397800216737759',
    ],
    [
        'title' => 'Marvellous lake destination eco-friendly villa',
        'description' => 'Questa lussuosa Villa eco-friendly è situata direttamente sul Lago di Como, a Brienno, con un molo privato per le barche e accesso diretto al lago con una scala in acciaio.
        La Villa è di nuova costruzione seguendo tutti i criteri di un\'ecologia di classe A+ con pannelli solari per alimentare una pompa di calore e pannelli in silicio per isolare termicamente l\'intera casa.
        Il design degli interni è bello e moderno, etichettato Lema, Cassina, B&B e Clei',
        'price' => '1280',
        'rooms' => '3',
        'beds' => '6',
        'bathrooms' => '4',
        'square_meters' => '250',
        'image' => 'apartments_img/apartment_16.webp',
        'is_visible' => '1',
        'address' => 'Roma, Lazio',
        'latitude' => '41.92208593461244',
        'longitude' => '12.429762698428634',
    ],
    [
        'title' => 'Glass House & SPA',
        'description' => 'Una casa di vetro situata su una bellissima collina nel cuore del Monferrato (patrimonio UNESCO), la Glass House offre un’incredibile vista a 360, una camera da letto ricca di comfort, un elegante soggiorno, una cucina completamente attrezzata, un bagno in marmo toscano, Sauna ed Hammam.
        È dotata di tecnologia domotica d’avanguardia, camino, TV. ecc.
        Nelle vicinanze: ottimi ristoranti, golf 36 buche, cavalli ed eccellenti cantine.
        Soggiornare nella Glass House 7* è davvero un\'esperienza unica!',
        'price' => '679',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '80',
        'image' => 'apartments_img/apartment_17.webp',
        'is_visible' => '1',
        'address' => 'Aosta, Valle d\'Aosta',
        'latitude' => '45.760381954034436',
        'longitude' => '7.275903765541708',
    ],
    [
        'title' => 'Trulli di Alberobello Puglia',
        'description' => 'I Trulli di Alberobello Puglia sono situati nel cuore della Valle d’Itria, a soli 3 km dal centro di Alberobello.
        Il trullo è dotato di 1 letto matrimoniale, 1 Alcova con letto singolo, 1 bagno, zona living, cucina abitabile, sala da pranzo, TV, Wifi e AC.',
        'price' => '300',
        'rooms' => '2',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '80',
        'image' => 'apartments_img/apartment_18.webp',
        'is_visible' => '1',
        'address' => 'Alberobello, Puglia',
        'latitude' => '40.78298168134093',
        'longitude' => '17.23718053564645',
    ],
    [
        'title' => 'B&B La Pusianella Suite',
        'description' => 'Il B&B La Pusianella nasce in una villa dell\'800, ristrutturata mantenendone il fascino originale. Il giardino all\'italiana si affaccia direttamente sul lago di Pusiano, uno specchio d\'acqua dall\'atmosfera rilassante. Sono disponibili 3 camere.',
        'price' => '130',
        'rooms' => '2',
        'beds' => '2',
        'bathrooms' => '2',
        'square_meters' => '80',
        'image' => 'apartments_img/apartment_19.webp',
        'is_visible' => '1',
        'address' => 'Eupilio, Lombardia',
        'latitude' => '45.79868062789312',
        'longitude' => '9.252468132135586',
    ],
    [
        'title' => 'Container Suite: sospeso tra terra e mare',
        'description' => 'Uno scrigno sofisticato, accogliente, immerso nella natura e dall’inconfondibile stile. Situato a Terrasini, in una meravigliosa valle affacciata sulla costa del Golfo di Castellammare, Container Suite, circondato da una rigogliosa distesa di fichi d’india, si integra nel paesaggio in perfetta armonia con il territorio circostante.',
        'price' => '175',
        'rooms' => '2',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '20',
        'image' => 'apartments_img/apartment_20.webp',
        'is_visible' => '1',
        'address' => 'Palermo, Sicilia',
        'latitude' => '38.16746176965482',
        'longitude' => '13.367662085450888',
    ],
    [
        'title' => 'La Stalla - Casa San Gabriel',
        'description' => 'Cottage con 1 camera da letto situato nella proprietà di Casa San Gabriel, immerso nella splendida campagna umbra, ha accesso agli ampi giardini e alla piscina. Il cottage è un completo self catering studio cottage con 1 letto matrimoniale o due letti singoli e aria condizionata.',
        'price' => '120',
        'rooms' => '2',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '80',
        'image' => 'apartments_img/apartment_21.webp',
        'is_visible' => '1',
        'address' => 'Perugia, Umbria',
        'latitude' => '43.11672344256808',
        'longitude' => '12.392402495817642',
    ],
    [
        'title' => 'Dream House',
        'description' => 'Prestigiosa Villa composta da sei camere doppie tutte con bagno privato, piscina privata e giardino.
        Posizionata a pochi minuti dalle spiagge di Scopello.',
        'price' => '334',
        'rooms' => '6',
        'beds' => '7',
        'bathrooms' => '8',
        'square_meters' => '200',
        'image' => 'apartments_img/apartment_22.webp',
        'is_visible' => '1',
        'address' => 'Palermo, Sicilia',
        'latitude' => '38.11428013025524',
        'longitude' => '13.520713174063516',
    ],
    [
        'title' => 'Toscana vera sulle colline di Siena e Volterra',
        'description' => 'Bellissimo appartamento appena ristrutturato in tipico stile toscano, all\'interno di un antico borgo nel cuore delle colline tra Siena e Volterra. 2 bagni, 5 posti letto, cucina con forno a microonde, forno tradizionale e lavastoviglie! Grande piscina, tanto spazio esterno e massimo relax!',
        'price' => '60',
        'rooms' => '1',
        'beds' => '3',
        'bathrooms' => '2',
        'square_meters' => '70',
        'image' => 'apartments_img/apartment_23.webp',
        'is_visible' => '1',
        'address' => 'Firenze, Toscana',
        'latitude' => '43.75316857990088',
        'longitude' => '11.262970235937392',
    ],
    [
        'title' => 'Appartamento Blue Hour',
        'description' => 'Il nostro delizioso appartamento, dotato di cucina bagno, veranda e giardino, gode di una posizione unica.
        I nostri ospiti godono di una veranda esclusiva
        I posti letto sono in totale 3, due nella camera da letto e uno aggiuntivo nella stessa stanza. La camera è molto ampia e si affaccia sulle vigne di Carignano.
        Siamo in una posizione strategica, dalla quale si possono raggiungere le più belle località balneari e archeologiche del Sulcis.
        Ideale per gli amanti del surf, kite e wind surf',
        'price' => '40',
        'rooms' => '1',
        'beds' => '2',
        'bathrooms' => '1',
        'square_meters' => '70',
        'image' => 'apartments_img/apartment_24.webp',
        'is_visible' => '1',
        'address' => 'Cagliari, Sardegna',
        'latitude' => '39.246013877433015',
        'longitude' => '9.24468508563379',
    ],
    [
        'title' => 'View a Centuries-Old Courtyard from a Private Palace Window',
        'description' => 'Bring the whole family to share in a deeply authentic Venetian experience within an 800-year-old palace. Lush draperies frame arched windows, baroque ceramics cover floors, ornate tapestries hang in bedrooms, and historic tomes fill library shelves.',
        'price' => '334',
        'rooms' => '3',
        'beds' => '4',
        'bathrooms' => '2',
        'square_meters' => '70',
        'image' => 'apartments_img/apartment_25.webp',
        'is_visible' => '1',
        'address' => 'Venezia, Veneto',
        'latitude' => '45.43818307417485',
        'longitude' => '12.329244842238875',
    ],
    [
        'title' => 'Vivi lo stile veneziano in un appartamento incantevole ed elegante',
        'description' => 'Bring the whole family to share in a deeply authentic Venetian experience within an 800-year-old palace. Lush draperies frame arched windows, baroque ceramics cover floors, ornate tapestries hang in bedrooms, and historic tomes fill library shelves.',
        'price' => '145',
        'rooms' => '2',
        'beds' => '3',
        'bathrooms' => '1',
        'square_meters' => '70',
        'image' => 'apartments_img/apartment_26.webp',
        'is_visible' => '1',
        'address' => 'Venezia, Veneto',
        'latitude' => '45.43719468104812',
        'longitude' => '12.325715157821714',
    ],
    [
        'title' => 'Canal View Residence',
        'description' => 'Un intero appartamento con un arredamento in stile veneziano, in un palazzo privato del 1600, con una VISTA MOZZAFIATO.
        Situato al 1 ° piano, l\'appartamento ha una grande camera da letto con un letto matrimoniale.
        Il bagno è spazioso e dotato di una grande doccia.La cucina è completamente attrezzata con frigorifero, tostapane, bollitore e macchina Nespresso.
        L\'ingresso si apre su una zona giorno molto grande con una vista sul canale, dove è possibile sedersi e fondamentalmente toccare l\'acqua mentre si sta godendo un bicchiere di vino.',
        'price' => '400',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '70',
        'image' => 'apartments_img/apartment_27.webp',
        'is_visible' => '1',
        'address' => 'Venezia, Veneto',
        'latitude' => '45.43428755290524',
        'longitude' => '12.33891819103043',
    ],
    [
        'title' => 'Appartamento colorato affacciato sul Rio Marin Canal',
        'description' => 'Scegli tra affacciarti sulle lussureggianti piante verdi da un lato e sul canale Rio Marin dall\'altro. La casa è piena di colori vivaci con dipinti sorprendenti e tappeti decorativi. Vanta un giardino privato verdeggiante sul retro.
        Possiamo avere 2 ospiti in più (per un totale di 8). Non esitare a contattarci direttamente
        È molto facile raggiungere la nostra casa, a 5 minuti a piedi dalla stazione ferroviaria e 10 dal parcheggio di autobus e auto a Piazzale Roma.
        Dista 3 minuti a piedi da Riva di Biasio e 5 dalle fermate del vaporetto S. Tomà.',
        'price' => '330',
        'rooms' => '3',
        'beds' => '7',
        'bathrooms' => '2',
        'square_meters' => '70',
        'image' => 'apartments_img/apartment_28.webp',
        'is_visible' => '1',
        'address' => 'Venezia, Veneto',
        'latitude' => '45.432864016721226',
        'longitude' => '12.330174254555075',
    ],
    [
        'title' => 'Luxury, RialtoVenezia Amazing wiev',
        'description' => 'Attico straordinaria bellezza, arredamento veneziano ,terrazza spaziosa che domina sul Canal Grande, quarto piano, vista magnifica sul ponte di Rialto, quartiere San Polo, centro nevralgico di Venezia, 10 min a piedi da Piazza San Marco, 2 min dal mercato, fermata di Rialto del vaporetto a 3 min, Gondole sotto casa',
        'price' => '800',
        'rooms' => '2',
        'beds' => '3',
        'bathrooms' => '2',
        'square_meters' => '70',
        'image' => 'apartments_img/apartment_29.webp',
        'is_visible' => '1',
        'address' => 'Venezia, Veneto',
        'latitude' => '45.43374759513135',
        'longitude' => '12.337519161194374',
    ],
    [
        'title' => 'Ponte Vecchio Luxury Apartament',
        'description' => 'Incredibile appartamento letteralmente su Ponte Vecchio, nella storica torre della famiglia Amidei. Completamente arredato, con un design molto efficiente e rifinito in ogni dettaglio. In un raggio di soli duecento metri si trova la maggior parte del patrimonio artistico fiorentino.',
        'price' => '333',
        'rooms' => '2',
        'beds' => '4',
        'bathrooms' => '1',
        'square_meters' => '70',
        'image' => 'apartments_img/apartment_30.webp',
        'is_visible' => '1',
        'address' => 'Firenze, Toscana',
        'latitude' => '43.76834466014821',
        'longitude' => '11.2583752584287',
    ],
    [
        'title' => 'Appartamento di lusso vicino al Museo del Bargello. Via Giraldi',
        'description' => 'Spettacolare appartamento situato sull\'iconica Via Giraldi, nel cuore di Firenze, che offre un mix armonioso di eleganza e comfort.',
        'price' => '388',
        'rooms' => '3',
        'beds' => '3',
        'bathrooms' => '3',
        'square_meters' => '70',
        'image' => 'apartments_img/apartment_31.webp',
        'is_visible' => '1',
        'address' => 'Firenze, Toscana',
        'latitude' => '43.76891037173859',
        'longitude' => '11.253079588164413',
    ],
    [
        'title' => 'IL MAGNIFICO',
        'description' => 'Appartamento in pieno centro storico a due passi dal Duomo di Firenze e facile da raggiungere perche a 5 minuti dalla stazione di santa Maria Novella in macchina con le comodità di avere tutti i negozi vicino casa.Con un ampio ed elegante salotto,deu camere da letto di cui una matrimoniale e l\'altra due letti singoli.due bagni con doccia,una sala da pranzo e una cucina.Non esitate a contattarmi per qualsiasi informazione.Don\'t hesitate to contact me for any information',
        'price' => '300',
        'rooms' => '2',
        'beds' => '6',
        'bathrooms' => '2',
        'square_meters' => '70',
        'image' => 'apartments_img/apartment_32.webp',
        'is_visible' => '1',
        'address' => 'Firenze, Toscana',
        'latitude' => '43.76989469715134',
        'longitude' => '11.259330985902428',
    ],
    [
        'title' => 'Mamo Florence - Appartamento Gastone',
        'description' => 'Tipico appartamento fiorentino situato al secondo piano senza ascensore.',
        'price' => '186',
        'rooms' => '2',
        'beds' => '5',
        'bathrooms' => '2',
        'square_meters' => '70',
        'image' => 'apartments_img/apartment_33.webp',
        'is_visible' => '1',
        'address' => 'Firenze, Toscana',
        'latitude' => '43.76413741552109',
        'longitude' => '11.259254110934366',
    ],
    [
        'title' => 'IGIENIZZATO, self check-in Incredibile stazione SMN',
        'description' => 'Vicino alla stazione ferroviaria S. M.N. e collegamenti di trasporto ( autobus/treno per l\'aeroporto e le città circostanti, negozi outlet The Mall) a pochi passi da tutti i punti di riferimento, centro storico e negozi. Luminoso e nuovo, soffitto dipinto dell\'800, confortevole.
        Self check-in per arrivi in ritardo.',
        'price' => '230',
        'rooms' => '2',
        'beds' => '3',
        'bathrooms' => '2',
        'square_meters' => '70',
        'image' => 'apartments_img/apartment_34.webp',
        'is_visible' => '1',
        'address' => 'Firenze, Toscana',
        'latitude' => '43.76825405161666',
        'longitude' => '11.245960360564002',
    ],
    [
        'title' => 'Appartamento 3A',
        'description' => 'Appartamento situato nel cuore del centro storico di Firenze, in un palazzo storico fiorentino proprio davanti alla Basilica di Santa Croce, visibile dalle finestre del soggiorno a meno di 10 metri in linea d\'aria. Un\'atmosfera unica nel centro storico di Firenze!',
        'price' => '335',
        'rooms' => '2',
        'beds' => '4',
        'bathrooms' => '1',
        'square_meters' => '70',
        'image' => 'apartments_img/apartment_35.webp',
        'is_visible' => '1',
        'address' => 'Firenze, Toscana',
        'latitude' => '43.774973684295475',
        'longitude' => '11.266211567826861',
    ],
    [
        'title' => 'Lux Palace Max',
        'description' => 'Bellissimo appartamento al primo piano di un palazzo storico fiorentino con affreschi, ampie vetrate e balcone.
        È composto da 4 camere da letto con 3 bagni privati: 2 camere matrimoniali sono private, 1 camera matrimoniale è loft su un ampio soggiorno dove si trova 1 divano e 1 divano letto matrimoniale.
        Cucina completa indipendente, lavastoviglie e lavatrice.
        Si trova nel centro storico di Santa Croce, vicino al fiume Arno e a Piazzale Michelangelo.
        Parcheggio privato disponibile tutti i giorni a 20€ in macchina, 30€ al giorno per un furgone.',
        'price' => '288',
        'rooms' => '4',
        'beds' => '5',
        'bathrooms' => '3',
        'square_meters' => '120',
        'image' => 'apartments_img/apartment_36.webp',
        'is_visible' => '1',
        'address' => 'Firenze, Toscana',
        'latitude' => '43.762379511276734',
        'longitude' => '11.25973015319559',
    ],
    [
        'title' => 'Colosseo moderno dell\'appartamento a Domvlvs',
        'description' => 'Uno splendido appartamento elegante e recentemente ristrutturato situato di fronte al Colosseo e al Foro Romano, nel cuore del centro storico della Città Eterna, a pochi passi da Piazza Venezia e dal Pantheon. L\'appartamento si trova al primo piano di un classico edificio romano. Il nostro staff sarà lieto di accogliere gli ospiti e offrire loro un\'esperienza memorabile nella Città Eterna.',
        'price' => '480',
        'rooms' => '3',
        'beds' => '3',
        'bathrooms' => '2',
        'square_meters' => '110',
        'image' => 'apartments_img/apartment_37.webp',
        'is_visible' => '1',
        'address' => 'Roma, Lazio',
        'latitude' => '41.89600772850795',
        'longitude' => '12.493174956828272',
    ],
    [
        'title' => 'Suite Colonna - San Giovanni SweetLife Apartment 2',
        'description' => 'Un appartamento ristrutturato ubicato a pochi passi dalla Basilica di San Giovanni e dalla Scala Santa. Grazie alla metropolitana, a soli 300 metri da casa, sarà possibile raggiungere in pochi minuti il centro storico della città.',
        'price' => '378',
        'rooms' => '2',
        'beds' => '4',
        'bathrooms' => '1',
        'square_meters' => '100',
        'image' => 'apartments_img/apartment_38.webp',
        'is_visible' => '1',
        'address' => 'Roma, Lazio',
        'latitude' => '41.90200053711259',
        'longitude' => '12.5438188486471',
    ],
    [
        'title' => 'K-In the center of Rome',
        'description' => 'Grazioso e accogliente appartamento nel centro di Roma. A 100 metri dalla stazione della metropolitana Re Di Roma 

        IL CHECK IN E\' ALLE 15 E\' POSSIBILE FISSARE UN ALTRO ORARIO MA E\' NECESSARIO ACCORDARSI ALMENO UN GIORNO PRIMA',
        'price' => '186',
        'rooms' => '3',
        'beds' => '4',
        'bathrooms' => '1',
        'square_meters' => '80',
        'image' => 'apartments_img/apartment_39.webp',
        'is_visible' => '1',
        'address' => 'Roma, Lazio',
        'latitude' => '41.91409768221611',
        'longitude' => '12.489905853117632',
    ],
    [
        'title' => 'Appartamento bianco Napoleone',
        'description' => 'Accogliente e nuovo appartamento a soli 5 minuti a piedi dalla stazione centrale. Elegante e dotato di ogni comfort, è composto da 3 camere da letto, un soggiorno  una cucina e 2  bagni . Wi-fi , lenzuola e asciugamani sono inclusi. Metropolitana\stazione ferroviaria si trova a 5 minuti a piedi e un mercato si trova a 50 metri dall\'appartamento La zona è piena di ristoranti e bar e ho una lista di luoghi consigliati:)',
        'price' => '510',
        'rooms' => '3',
        'beds' => '4',
        'bathrooms' => '2',
        'square_meters' => '90',
        'image' => 'apartments_img/apartment_40.webp',
        'is_visible' => '1',
        'address' => 'Roma, Lazio',
        'latitude' => '41.88734428939035',
        'longitude' => '12.489194880125902',
    ],
    [
        'title' => 'Una notte nella palude di Shrek, ora su Boolbnb',
        'description' => 'C’era una volta un asino molto loquace che accettò di fare da custode della palude di Shrek e prima di rimettersi in viaggio, decise di invitare le persone a trascorrere una notte da orchi proprio nella palude, disponibile ora per un soggiorno unico solo su Boolbnb.',
        'price' => '2',
        'rooms' => '1',
        'beds' => '1',
        'bathrooms' => '1',
        'square_meters' => '90',
        'image' => 'apartments_img/apartment_41.webp',
        'is_visible' => '1',
        'address' => 'Roma, Lazio',
        'latitude' => '41.88734428939035',
        'longitude' => '12.489194880125902',
    ],
    [
        'title' => 'La Casa Bianca... a Roma',
        'description' => 'La Casa Bianca è la residenza ufficiale dell\'imperatore romano e sede della presidenza stessa. Si trova al numero 1600 di Pennsylvania Avenue a Roma ed è stata la residenza di ogni imperatore romano da John Adams in poi.',
        'price' => '99999',
        'rooms' => '100',
        'beds' => '200',
        'bathrooms' => '999',
        'square_meters' => '342000',
        'image' => 'apartments_img/apartment_42.jpg',
        'is_visible' => '1',
        'address' => 'Roma, Lazio',
        'latitude' => '41.88734428939035',
        'longitude' => '12.489194880125902',
    ]
];
